[workspace]
members = [
    "locked-astroport-vault",
    "test-helpers"
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
astroport               = "2.8.0"
apollo-cw-asset         = "0.1.2"
apollo-utils            = "0.1.1"
cosmwasm-schema         = "1.1.0"
cosmwasm-std            = "1.1.0"
cw-dex                  = { version = "0.3.1", features = ["astroport"] }
cw-ownable              = "0.5.1"
cw-storage-plus         = "1.1.0"
cw-utils                = "1.0.1"
cw-vault-standard       = { version = "0.3.2", features = ["lockup", "force-unlock"] }
cw2                     = "1.1.0"
cw20                    = "1.1.0"
osmosis-std             = "0.14"
thiserror               = "1.0.43"
cw-dex-router           = { version = "0.1.0", features = ["library"] }
strum                   = { version = "0.25.0", features = ["derive"] }
liquidity-helper        = "0.1.0"
locked-astroport-vault  = { version = "0.1.0", path = "./locked-astroport-vault" }

# Dev dependencies
cw-it                               = { version = "0.1.1", features = ["astroport"] }
cw-vault-standard-test-helpers      = { version = "0.4.0-rc.2", features = ["lockup", "force-unlock"] }
locked-astroport-vault-test-helpers = { version = "0.1.0", path = "../test-helpers" }
proptest                            = "1.2.0"
test-case                           = "3.1.0"
