[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
# If you bump this version, verify RUST_VERSION correctness
RUST_OPTIMIZER_VERSION = "0.13.0"
# Use rust version from rust-optimizer Dockerfile (see https://github.com/CosmWasm/rust-optimizer/blob/main/Dockerfile#L1)
# to be sure that we compile / test against the same version
RUST_VERSION = "1.69.0"

[tasks.rust-optimizer]
cwd = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}"
script = """
if [[ $(arch) == "arm64" ]]; then
  image="cosmwasm/workspace-optimizer-arm64:${RUST_OPTIMIZER_VERSION}"
else
  image="cosmwasm/workspace-optimizer:${RUST_OPTIMIZER_VERSION}"
fi
docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  ${image}
"""

[tasks.format]
toolchain = "nightly"
install_crate = { crate_name = "rustfmt-nightly", rustup_component_name = "rustfmt-preview", binary = "rustfmt", test_arg = "--help" }
command = "cargo"
args = ["fmt", "--all", "--", "--emit=files","--verbose"]
[tasks.format-check]
toolchain = "nightly"
install_crate = { crate_name = "rustfmt-nightly", rustup_component_name = "rustfmt-preview", binary = "rustfmt", test_arg = "--help" }
command = "cargo"
args = ["fmt", "--all", "--","--verbose", "--check"]

# This task requires the `cargo-udeps` package: https://crates.io/crates/cargo-udeps
[tasks.udeps]
toolchain = "nightly"
command = "cargo"
args = ["udeps"]

[tasks.deny]
command = "cargo"
args = ["deny", "check"]

[tasks.check]
command = "cargo"
args = ["check"]

[tasks.clippy-check]
toolchain = "nightly"
command = "cargo"
args = ["clippy","--all-features","--","-D","warnings"]
[tasks.clippy-fix]
toolchain = "nightly"
command = "cargo"
args = ["clippy","--fix","--allow-staged","--","-D","warnings"]

[tasks.todo-check]
script = { file = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/scripts/todo-lint.sh", absolute_path = true }

# This task requires the `cargo-tarpaulin` package: https://crates.io/crates/cargo-tarpaulin
[tasks.cov]
command = "cargo"
args = [
    "tarpaulin",
    "--ignore-tests",
    "-o",
    "Lcov",
    "--output-dir",
    "target/tarpaulin",
]

[tasks.docs]
command = "cargo"
args = [
    "doc",
    "--target-dir",
    "docs",
    "--color",
    "never",
    "--no-deps",
    "--workspace",
    "--exclude",
    "'cosmwasm*'",
    "--exclude",
    "'cw*'",
    "--release",
]

# This task requires the `cargo-machete` package: https://crates.io/crates/cargo-machete
[tasks.machete-check]
command = "cargo"
args = ["machete"]
[tasks.machete-fix]
command = "cargo"
args = ["machete", "--fix"]

# Run automatically on "cargo make". This is the default task. We keep all the
# default tasks and add our own "custom" task.
[tasks.dev-test-flow]
run_task = "custom-default"

# Custom tasks to run on "cargo make"
[tasks.custom-default]
dependencies = ["deny", "clippy-fix", "docs", "machete-fix"]

# Wasm build of test contract
[tasks.wasm]
command = "cargo"
args = [
    "build",
    "--target",
    "wasm32-unknown-unknown",
    "--lib",
    "--release",
    "--package",
    "osmosis-test-contract"
]

# Docs and Test coverage are not run by default. Can run all with "cargo make all".
[tasks.all]
dependencies = ["dev-test-flow", "custom-default", "cov"]
