[package]
name = "locked-astroport-vault-test-helpers"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
cosmwasm-std                    = { workspace = true }
cw20                            = { workspace = true }
cw-dex                          = { workspace = true }
cw-it                           = { workspace = true, features = ["astroport"] }
cw-vault-standard-test-helpers  = { workspace = true }
locked-astroport-vault          = { workspace = true }